name: goldooni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_osm_plugin: ^1.4.2
  flutter_svg: ^2.2.1
  fpdart: ^1.1.1
  loading_animation_widget: ^1.3.0
  animate_do: ^4.2.0
  get_it: ^9.0.5
  shared_preferences: ^2.5.3
  flutter_styled_toast: ^2.2.1
  dio: ^5.9.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  geolocator: ^14.0.2
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/svg/
  - assets/png/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700

